### PR TITLE
Add some necessary license headers.

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by jklein24** [comment]
It turns out that Chromium's checklicenses.py only cares about the .travis-setup.sh file, but I figured I'd knock out a few others while I was in here.

**Comment by dstockwell** [comment]
Please recreate this pull request against the web-animations-next repo. Only releases occur here.

**Comment by jklein24** [comment]
Done in https://github.com/web-animations/web-animations-next/pull/289. Thanks!

**Comment by dstockwell** [comment]
Oops!

**Pull request closed without merging**
