### PR TITLE
Add missing version

### PR DESCRIPTION
**Pull request by chevdor**
See #51

### CODE REVIEW

**Comment by dstockwell** [comment]
We would prefer not to have to update too many version numbers when doing a new release. What is the bower.json version number needed for?

**Comment by samthor** [comment]
It's not needed, since `bower install` gets it from git tags.

**Comment by chevdor** [comment]
I am building webjars for Polymer (https://github.com/chevdor/webjars-polymer) and web-animations-js is a dependency.

I am not using bower itself but I parse the bower.json to know the version and what is the latest archive I can download to build the webjar. So far more than 99% of the bower components I went thru do provide a version and I am relying on that.

I understand that it is a little extra work to maintain that. I see you are using grunt, you may want to have a look at https://github.com/vojtajina/grunt-bump or one of the alternatives. It may provide a way to do it easily.

**Comment by tnga** [comment]
Why not use `package.json` for that ?

**Comment by chevdor** [comment]
@tnga I am not writing something just for web-animations-js and since the 100+ repo I am makeing webjars for are bower packages, I handle them all as such. Out of 130 repo, only 2 don´t have a version.

I don´t get your point about bower and npm, sorry. They are nice tools, yes...
I am sure you are nicely trying to help but proposing 'something else' as solution does not help.

Now concretely, bumping the version is supported by bower: http://bower.io/docs/api/#version

So including that to the release workflow would fix this 'issue' and keep things simple.

**Comment by ankon** [comment]
Bower's `version` is deprecated and ignored, so it seems wrong to add it. Relying on it when parsing basically means your whole process of producing the webjars is really fragile, and could break at any time. 

See https://github.com/bower/spec/blob/master/json.md#version

**Comment by alancutter** [comment]
Closing this given that bower's version property is deprecated.

**Pull request closed without merging**
