### PR TITLE
Added info regarding Angular 2

### PR DESCRIPTION
**Pull request by rmcsharry**

### CODE REVIEW

**Comment by justingrayston** [comment]
Have you tried this with PhantomJS?

I have just added the this polyfill and it works great on real browsers but CI fell over.

```
'Attempting to configure 'style' with descriptor '{"enumerable":true,"configurable":true}' on object '[object HTMLHtmlElement]' and got error, giving up: TypeError: Attempting to configurable attribute of unconfigurable property.'

TypeError: undefined is not a constructor (evaluating 'b.style._set(a.propertyName(c),d)')
  at webpack:///~/web-animations-js/web-animations.min.js:15:0
```

I noted that someone raised an issue over at PhantomJS https://github.com/ariya/phantomjs/issues/14222 but not sure that is the right place to report it.

I am thinking there should be a lot more people having the same error, but it errors the moment you add the polyfill, otherwise everything runs ok.

Try running `ng test --watch false --browsers PhantomJS`

**Comment by alancutter** [comment]
Thanks for the documentation contribution.
@matsko, is this an appropriate place for this info or is there somewhere in Angular that would be more visible for people potentially affected by this?

**Comment by filoxo** [comment]
My 2¢:

- [#itsJustAngular](http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html)
- I don't think this repo should be the source of truth for this. I'd like to see this in the official Angular docs instead.

**Comment by brgaulin** [comment]
Angular docs have this information now:
https://angular.io/guide/animations
and the following line is in polyfill.ts
```typescript
/**
 * Required to support Web Animations `@angular/animation`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
```

**Comment by rmcsharry** [comment]
@brgaulin  Thanks for that update. Since it's in the official docs now, we can close this without merging it.

**Pull request closed without merging**
